version: '3'
services:
  nest-backend:
    container_name: nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_TOKEN_EXPIRATION_TIME=${REDIS_TOKEN_EXPIRATION_TIME}
      - DATABASE=${DATABASE}
    env_file:
      - ./.env
    networks:
      - backend_network
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    networks:
      - backend_network

  redis:
    image: redis:7.0.12-alpine
    restart: on-failure
    ports:
      - '6379:6379'

    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/var/lib/redis/
    networks:
      - backend_network
networks:
  backend_network:
    driver: bridge

volumes:
  cache:
